# Variables para definir uns meta (GOAL)
# al ActionServer

geometry_msgs/msg/Pose goal

---
# Variables para definir el resultado
# del proceso del ActionServer

geometry_msgs/msg/Pose result_pose
bool success 
string string_result_message
---)
# Definicion de variables par el mensaje de 
# feeback 
geometry_msgs/msg/Pose current_pose
string log_info